import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {
  //     type: 'autogenerated', 
  //     dirName: '.'
  //   }
  // ],
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/introduction',
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/usage'
      ],
    },
    {
      type: 'category',
      label: 'Guides and Concepts',
      items: [
        {
          type: 'doc',
          label: 'Combining Sections',
          id: 'guides/combine-sections'
        },
        {
          type: 'doc',
          label: 'Connecting Task Flows',
          id: 'guides/connect-task-flows-together'
        },
        {
          type: 'category',
          label: 'Full Tutorials',
          items: [
            {
              type: 'category',
              label: 'Building with STRUDEL',
              items: [
                'guides/tutorials/basic-app-with-strudel/introduction',
                'guides/tutorials/basic-app-with-strudel/setup'
              ]
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Task Flows',
      // link: {
      //   type: 'generated-index',
      //   description: 'Learn about the most important Docusaurus concepts!',
      //   keywords: ['guides'],
      // },
      items: [
        'task-flows/overview',
        {
          type: 'category',
          label: 'Compare Data',
          items: [
            'task-flows/compare-data/usage',
            'task-flows/compare-data/config',
            'task-flows/compare-data/routes',
          ]
        },
        {
          type: 'category',
          label: 'Contribute Data',
          items: [
            'task-flows/contribute-data/config',
            'task-flows/contribute-data/routes',
          ]
        },
        {
          type: 'category',
          label: 'Explore Data',
          items: [
            'task-flows/explore-data/config',
            'task-flows/explore-data/routes',
          ]
        },
        {
          type: 'category',
          label: 'Monitor Activities',
          items: [
            'task-flows/monitor-activities/config',
            'task-flows/monitor-activities/routes',
          ]
        },
        {
          type: 'category',
          label: 'Run Computation',
          items: [
            'task-flows/run-computation/config',
            'task-flows/run-computation/routes',
          ]
        },
        {
          type: 'category',
          label: 'Search Data Repositories',
          items: [
            'task-flows/search-data-repositories/config',
            'task-flows/search-data-repositories/routes',
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/LabelValueTable',
        'components/LinearMeter',
      ],
    },
    {
      type: 'doc',
      label: 'CLI Reference',
      id: 'cli/reference'
    },
  ],
};

export default sidebars;
