/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as ExploreDataIndexImport } from './routes/explore-data/index';
import { Route as ExploreDataIdImport } from './routes/explore-data/$id';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const ExploreDataIndexRoute = ExploreDataIndexImport.update({
  id: '/explore-data/',
  path: '/explore-data/',
  getParentRoute: () => rootRoute,
} as any);

const ExploreDataIdRoute = ExploreDataIdImport.update({
  id: '/explore-data/$id',
  path: '/explore-data/$id',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/explore-data/$id': {
      id: '/explore-data/$id';
      path: '/explore-data/$id';
      fullPath: '/explore-data/$id';
      preLoaderRoute: typeof ExploreDataIdImport;
      parentRoute: typeof rootRoute;
    };
    '/explore-data/': {
      id: '/explore-data/';
      path: '/explore-data';
      fullPath: '/explore-data';
      preLoaderRoute: typeof ExploreDataIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/explore-data/$id': typeof ExploreDataIdRoute;
  '/explore-data': typeof ExploreDataIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/explore-data/$id': typeof ExploreDataIdRoute;
  '/explore-data': typeof ExploreDataIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/explore-data/$id': typeof ExploreDataIdRoute;
  '/explore-data/': typeof ExploreDataIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/explore-data/$id' | '/explore-data';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/explore-data/$id' | '/explore-data';
  id: '__root__' | '/' | '/explore-data/$id' | '/explore-data/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ExploreDataIdRoute: typeof ExploreDataIdRoute;
  ExploreDataIndexRoute: typeof ExploreDataIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreDataIdRoute: ExploreDataIdRoute,
  ExploreDataIndexRoute: ExploreDataIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/explore-data/$id",
        "/explore-data/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/explore-data/$id": {
      "filePath": "explore-data/$id.tsx"
    },
    "/explore-data/": {
      "filePath": "explore-data/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
